### ISSUE TITLE
[Feature] Support cross-namespace clusterclasses in cluster creation

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/capi-ui-extension#111]
Turtles will soon support the use of cluster classes in different namespaces than the cluster to be provisioned. The UI needs to be updated to support a new field during cluster creation: `classNamespace`. If no class namespace is selected, the default is to use the same namespace as the cluster.

**Comment by Danil-Grigorev** [comment]
https://github.com/kubernetes-sigs/cluster-api/issues/5673 is fixed, this will be added in the next turtles release with CAPI 1.9.5

**Comment by anmazzotti** [comment]
We could just have a "Cluster Namespace" in the second screen of Cluster creation. The UI currently uses the Class namespace's instead. However that will then need to be passed as classNamespace field:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster
  namespace: my-namespace
spec:
  topology:
    class: azure-something
    classNamespace: my-clusterclasses
```

This requires CAPI core provider to be >= v1.6.5, which raises the question if we should have feature gates based on CAPI core and maybe even Turtles versions.
