### ISSUE TITLE
Clusterclass: Unable to specify bool value for object variable type

### ISSUE THREAD

**Issue by cpinjani** [rancher/capi-ui-extension#119]
UI Extension: `v0.8.2`

**Steps**
- Create clusterclass from [template](https://github.com/rancher/turtles/blob/main/exp/clusterclass/config/samples/class1.yaml)
- Create cluster using above class
- On Variables step, for `podSecurityStandard` only string type can assigned in value for enabled property

```
- name: podSecurityStandard
    required: false
    schema:
      openAPIV3Schema:
        properties:
          enabled:
            default: true
            description: enabled enables the patches to enable Pod Security Standard
              via AdmissionConfiguration.
            type: boolean
```

![Image](https://github.com/user-attachments/assets/a2a24b36-4f4d-4121-81a8-3c9f7bd862f3)
