### ISSUE TITLE
Clusterclass: Add field for replicas count

### ISSUE THREAD

**Issue by cpinjani** [rancher/capi-ui-extension#120]
UI Extension: `v0.8.2`

**Steps**
- Create clusterclass from [template](https://github.com/rancher/turtles/blob/main/exp/clusterclass/config/samples/class1.yaml)
- Create cluster using above class
- Replicas field is not present for ControlPlane and Workers

Spec Snippet:
```
  topology:
    class: quick-start
    controlPlane:
      metadata: {}
      replicas: 3
    version: v1.30.3
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 3
```

![Image](https://github.com/user-attachments/assets/2e9f3fb0-7e77-4988-8427-be6830bb67fc)
