### ISSUE TITLE
Clusterclass: Add option to add Labels/Annotations while cluster creation

### ISSUE THREAD

**Issue by cpinjani** [rancher/capi-ui-extension#122]
UI Extension: `v0.8.2`

**Steps**
- Create clusterclass from [template](https://github.com/rancher/turtles/blob/main/exp/clusterclass/config/samples/class1.yaml)
- Create cluster using above class
- Till the cluster is not imported in Rancher, there is no option to add Labels/Annotations via CAPI menu

**Comment by gaktive** [comment]
Need to check whether the backend can support this between CAPI (creation time) and the provisioning cluster (where they're stored)

**Comment by gaktive** [comment]
^ This may be a Fleet question

**Comment by anmazzotti** [comment]
I think this is just about allowing labels and annotations at Cluster creation (from a ClusterClass).

The only goal here is to add for example `cni` or `ccm` labels to install apps onto the CAPI Cluster.
For example:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster-api.cattle.io/rancher-auto-import: "true"
    cloud-provider: azure
    cni: calico
  name: azure-quickstart
spec: 
.
.
.
```
