### ISSUE TITLE
Clusterclass: Variables should not be required by default

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher/capi-ui-extension#129]
While trying a docker quick-start ClusterClass, variables exposed on Cluster didn’t have required variables, all of them were optional. In UI these displayed variables were required, without default coming from example.

It seems to be not entirely convenient to type out all variable content by hand in the presence of example.

Here is the content of `ClusterClass` variables section. These variables are required, but also provide default: “”, which should be accepted unless changed to empty value.

```yaml
  variables:
  - name: imageRepository
    required: true
    schema:
      openAPIV3Schema:
        default: ""
        description: imageRepository sets the container registry to pull images from.
          If empty, nothing will be set and the from of kubeadm will be used.
        example: registry.k8s.io
        type: string
  - name: etcdImageTag
    required: true
    schema:
      openAPIV3Schema:
        default: ""
        description: etcdImageTag sets the tag for the etcd image.
        example: 3.5.3-0
        type: string
  - name: coreDNSImageTag
    required: true
    schema:
      openAPIV3Schema:
        default: ""
        description: coreDNSImageTag sets the tag for the coreDNS image.
        example: v1.8.5
        type: string
```
