### ISSUE TITLE
Unable to update custom CAPIProvider version

### ISSUE THREAD

**Issue by cpinjani** [rancher/capi-ui-extension#96]
### What steps did you take and what happened?

- Install turtles v0.11.0 on Rancher v2.9 via Rancher Dashboard
- Install custom providers eg. 
1. kubeadm-control-plane using YAML (do not provide version)
2. kubeadm-bootstrap using CAPI-UI extension, it creates using version
```
spec:
  configSecret:
    name: custom-credentials-xtczv
  features:
    clusterResourceSet: true
    clusterTopology: true
    machinePool: true
  fetchConfig:
    url: >-
      https://github.com/kubernetes-sigs/cluster-api/releases/v1.4.6/bootstrap-components.yaml
  name: kubeadm
  type: bootstrap
  variables: {}
  **version: v1.4.6**
```

![image](https://github.com/user-attachments/assets/1f85e637-bb61-4693-9175-15818e6d0820)

- Upgrade turtles to v0.12

kubeadm-control-plane is auto-upgraded to v1.7.3
`message: Updated to latest v1.7.3 version`

kubeadm-bootstrap stays on v1.4.6 and unable to upgrade using ClusterctlConfig
`message: Provider version update available. Current latest is v1.7.3`

### What did you expect to happen?

CAPIProvider version should be auto-upgraded or User able to upgrade custom CAPIProvider version

### Rancher Turtles version

v.0.12

### Label(s) to be applied

/kind bug
